controller_list:
  - name: jaco_trajectory_controller
    action_ns: trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - j2s7s300_joint_1
      - j2s7s300_joint_2
      - j2s7s300_joint_3
      - j2s7s300_joint_4
      - j2s7s300_joint_5
      - j2s7s300_joint_6
      - j2s7s300_joint_7
  #- name: gripper_actions
  #  action_ns: gripper_command
  #  type: GripperCommand
  #  default: true
  #  joints:
  #    - j2s7s300_robotiq_85_left_knuckle_joint
